service: mksmds

image: msmedes/mksmds

servers:
  web:
    - mksmds.com

proxy:
  ssl: true
  host: mksmds.com
  healthcheck:
    path: /up

registry:
  username: msmedes
  password:
    - KAMAL_REGISTRY_PASSWORD


builder:
  arch: amd64
  dockerfile: Dockerfile
